#List indexing

In [1]:
list1=[1,3,4,5,6,79,10]
list1

[1, 3, 4, 5, 6, 79, 10]

In [2]:
type(list1)

list

In [3]:
list1.index(79)#index function will work in case of list only

5

#Tuple Indexing

In [4]:
fruits = ("apple", "banana", "cherry","pineapple","orange")

In [5]:
type(fruits)

tuple

In [6]:
fruits.index('orange')

4

#Numpyarray indexing 

In [7]:
import numpy as np

In [8]:
arr=np.array(list1)

In [9]:
arr

array([ 1,  3,  4,  5,  6, 79, 10])

In [10]:
type(arr)

numpy.ndarray

To find the index of any element in numpy array please use where condition 

In [11]:
np.where(arr == 79)

(array([5], dtype=int64),)

In [12]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])

In [13]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
np.where(arr2d == 3)

(array([0], dtype=int64), array([2], dtype=int64))

In [15]:
arr2d[0][2]

3

#df indexing

In [16]:
import pandas as pd

In [17]:
df = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                        index=[0, 1, 2, 3])

In [18]:
df

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [19]:
df[df['A']=='A1'].index.values

array([1], dtype=int64)

In [20]:
df['newintvalues']=[1,3,4,6]

In [21]:
df

A   B   C   D  newintvalues
0  A0  B0  C0  D0             1
1  A1  B1  C1  D1             3
2  A2  B2  C2  D2             4
3  A3  B3  C3  D3             6

In [23]:
df[df['newintvalues']==3].index.values

array([1], dtype=int64)